; Daemon Pal - Compact user-space tool/library for process management.
; Copyright (C) 2024 Fabrika Charvat s.r.o. All rights reserved.
; Developed by Partoska Laboratory team, <https://lab.partoska.com>

[ls]
Id=0
App=/bin/ls
Dir=/opt
Arg=ls
Arg=-l
Arg=-h
Arg=-a
LogMaxSize=64
LogRotation=3
RestartSec=10

[pwd]
Id=3
App=pwd
Arg=pwd
Dir=/opt
LogMaxSize=8388608

[sleep]
Id=10
App=sleep
Dir=/opt
Arg=sleep
Arg=30

[printenv]
Id=20
App=printenv
Dir=/opt
Arg=printenv
Arg=ENV
Env=(Name=ENV,Value=STAGE)
