#!/bin/bash

# Daemon Pal - Documentation Generator
# Copyright (C) 2024 Fabrika Charvat s.r.o. All rights reserved.
# Developed by Partoska Laboratory team, <https://lab.partoska.com>
#
# MIT License
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#
# You can contact the author(s) via email at ask <at> partoska.com.

set -euo pipefail

# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# Configuration
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

PROJECT_NAME="Daemon Pal"
PROJECT_BRIEF="Compact user-space tool and library for process management"
PROJECT_VERSION="1.3.1"
PROJECT_LOGO="img/logo-mark_64.png"
INPUT_DIRS="src/lib/inc src/lib/src"
OUTPUT_DIR="docs"
DOXYFILE="Doxyfile.tmp"

# Default options
INCLUDE_PRIVATE=0
CLEAN_FIRST=0
VERBOSE=0
OUTPUT_FORMAT="html"
API_ONLY=1

# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# Functions
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

usage() {
    cat << EOF
Usage: $0 [OPTIONS]

Generate documentation for Daemon Pal using Doxygen.

OPTIONS:
    -h, --help          Show this help message
    -c, --clean         Clean existing documentation before generation
    -p, --private       Include private/internal documentation from source files
    -v, --verbose       Enable verbose output
    -f, --format FORMAT Set output format (html, latex, man, xml) [default: html]
    -o, --output DIR    Set output directory [default: docs]
    -x, --extra         Generate full documentation (not dpal.h and dpaltypes.h only)

EXAMPLES:
    $0                  Generate HTML documentation
    $0 -c               Clean and regenerate documentation
    $0 -p -v            Generate with private docs and verbose output
    $0 -f latex         Generate LaTeX documentation
    $0 -a               Generate API-only documentation (dpal.h and dpaltypes.h)

EOF
}

log() {
    echo "doc.sh: $*" >&2
}

verbose() {
    if [[ $VERBOSE -eq 1 ]]; then
        log "$*"
    fi
}

error() {
    log "ERROR: $*"
    exit 1
}

check_doxygen() {
    if ! command -v doxygen >/dev/null 2>&1; then
        error "Doxygen is not installed. Please install it first."
    fi

    verbose "Using Doxygen: $(doxygen --version)"
}

clean_docs() {
    if [[ -d "$OUTPUT_DIR" ]]; then
        log "Cleaning existing documentation in $OUTPUT_DIR/"
        rm -rf "$OUTPUT_DIR"
    fi
}

generate_doxyfile() {
    local doxyfile="$1"
    local include_private="$2"

    verbose "Generating Doxygen configuration: $doxyfile"

    # Configure input files based on API_ONLY setting
    local input_files
    local strip_path_setting
    if [[ $API_ONLY -eq 1 ]]; then
        input_files="src/lib/inc/dpal.h src/lib/inc/dpaltypes.h"
        strip_path_setting="src/lib/inc/"
        verbose "API-only mode: Including only dpal.h and dpaltypes.h"
    else
        input_files="$(echo $INPUT_DIRS | tr ' ' '\n' | grep -v '^$' | tr '\n' ' ') README.md"
        strip_path_setting=""
    fi

    cat > "$doxyfile" << EOF
# Doxygen configuration for $PROJECT_NAME
# Generated by doc.sh

#---------------------------------------------------------------------------
# Project related configuration options
#---------------------------------------------------------------------------
DOXYFILE_ENCODING      = UTF-8
PROJECT_NAME           = "$PROJECT_NAME"
PROJECT_NUMBER         = $PROJECT_VERSION
PROJECT_BRIEF          = "$PROJECT_BRIEF"
PROJECT_LOGO           = $PROJECT_LOGO
OUTPUT_DIRECTORY       = $OUTPUT_DIR
CREATE_SUBDIRS         = NO
ALLOW_UNICODE_NAMES    = NO
OUTPUT_LANGUAGE        = English
BRIEF_MEMBER_DESC      = YES
REPEAT_BRIEF           = YES
ABBREVIATE_BRIEF       =
ALWAYS_DETAILED_SEC    = NO
INLINE_INHERITED_MEMB  = NO
FULL_PATH_NAMES        = YES
STRIP_FROM_PATH        = $strip_path_setting
STRIP_FROM_INC_PATH    = $strip_path_setting
SHORT_NAMES            = NO
JAVADOC_AUTOBRIEF      = YES
QT_AUTOBRIEF           = NO
MULTILINE_CPP_IS_BRIEF = NO
INHERIT_DOCS           = YES
SEPARATE_MEMBER_PAGES  = YES
TAB_SIZE               = 2
ALIASES                =
TCL_SUBST              =
OPTIMIZE_OUTPUT_FOR_C  = YES
OPTIMIZE_OUTPUT_JAVA   = NO
OPTIMIZE_FOR_FORTRAN   = NO
OPTIMIZE_OUTPUT_VHDL   = NO
EXTENSION_MAPPING      =
MARKDOWN_SUPPORT       = YES
AUTOLINK_SUPPORT       = YES
TOC_INCLUDE_HEADINGS   = 5
BUILTIN_STL_SUPPORT    = NO
CPP_CLI_SUPPORT        = NO
SIP_SUPPORT            = NO
IDL_PROPERTY_SUPPORT   = YES
DISTRIBUTE_GROUP_DOC   = NO
GROUP_NESTED_COMPOUNDS = NO
SUBGROUPING            = YES
INLINE_GROUPED_CLASSES = NO
INLINE_SIMPLE_STRUCTS  = NO
TYPEDEF_HIDES_STRUCT   = NO
LOOKUP_CACHE_SIZE      = 0

#---------------------------------------------------------------------------
# Build related configuration options
#---------------------------------------------------------------------------
EXTRACT_ALL            = YES
EXTRACT_PRIVATE        = $([ "$include_private" -eq 1 ] && echo "YES" || echo "NO")
EXTRACT_PACKAGE        = NO
EXTRACT_STATIC         = $([ "$include_private" -eq 1 ] && echo "YES" || echo "NO")
EXTRACT_LOCAL_CLASSES  = $([ "$include_private" -eq 1 ] && echo "YES" || echo "NO")
EXTRACT_LOCAL_METHODS  = $([ "$include_private" -eq 1 ] && echo "YES" || echo "NO")
EXTRACT_ANON_NSPACES   = NO
HIDE_UNDOC_MEMBERS     = NO
HIDE_UNDOC_CLASSES     = $([ "$include_private" -eq 1 ] && echo "NO" || echo "YES")
HIDE_FRIEND_COMPOUNDS  = NO
HIDE_IN_BODY_DOCS      = NO
INTERNAL_DOCS          = $([ "$include_private" -eq 1 ] && echo "YES" || echo "NO")
CASE_SENSE_NAMES       = YES
HIDE_SCOPE_NAMES       = NO
HIDE_COMPOUND_REFERENCE= NO
SHOW_INCLUDE_FILES     = YES
SHOW_GROUPED_MEMB_INC  = NO
FORCE_LOCAL_INCLUDES   = NO
INLINE_INFO            = YES
SORT_MEMBER_DOCS       = YES
SORT_BRIEF_DOCS        = NO
SORT_MEMBERS_CTORS_1ST = NO
SORT_GROUP_NAMES       = NO
SORT_BY_SCOPE_NAME     = NO
STRICT_PROTO_MATCHING  = NO
GENERATE_TODOLIST      = YES
GENERATE_TESTLIST      = YES
GENERATE_BUGLIST       = YES
GENERATE_DEPRECATEDLIST= YES
ENABLED_SECTIONS       =
MAX_INITIALIZER_LINES  = 30
SHOW_USED_FILES        = YES
SHOW_FILES             = YES
SHOW_NAMESPACES        = YES
FILE_VERSION_FILTER    =
LAYOUT_FILE            =
CITE_BIB_FILES         =

#---------------------------------------------------------------------------
# Configuration options related to warning and progress messages
#---------------------------------------------------------------------------
QUIET                  = $([ "$VERBOSE" -eq 1 ] && echo "NO" || echo "YES")
WARNINGS               = YES
WARN_IF_UNDOCUMENTED   = YES
WARN_IF_DOC_ERROR      = YES
WARN_NO_PARAMDOC       = YES
WARN_FORMAT            = "\$file:\$line: \$text"
WARN_LOGFILE           =

#---------------------------------------------------------------------------
# Configuration options related to the input files
#---------------------------------------------------------------------------
INPUT                  = $input_files
INPUT_ENCODING         = UTF-8
FILE_PATTERNS          = *.c *.h *.md *.ini
RECURSIVE              = YES
EXCLUDE                =
EXCLUDE_SYMLINKS       = NO
EXCLUDE_PATTERNS       = */build/* */3rdparty/*
EXCLUDE_SYMBOLS        =
EXAMPLE_PATH           =
EXAMPLE_PATTERNS       =
EXAMPLE_RECURSIVE      = NO
IMAGE_PATH             =
INPUT_FILTER           =
FILTER_PATTERNS        =
FILTER_SOURCE_FILES    = NO
FILTER_SOURCE_PATTERNS =
USE_MDFILE_AS_MAINPAGE = README.md

#---------------------------------------------------------------------------
# Configuration options related to source browsing
#---------------------------------------------------------------------------
SOURCE_BROWSER         = $([ "$include_private" -eq 1 ] && echo "YES" || echo "NO")
INLINE_SOURCES         = NO
STRIP_CODE_COMMENTS    = YES
REFERENCED_BY_RELATION = YES
REFERENCES_RELATION    = YES
REFERENCES_LINK_SOURCE = YES
SOURCE_TOOLTIPS        = YES
USE_HTAGS              = NO
VERBATIM_HEADERS       = YES

#---------------------------------------------------------------------------
# Configuration options related to the alphabetical class index
#---------------------------------------------------------------------------
ALPHABETICAL_INDEX     = YES
COLS_IN_ALPHA_INDEX    = 5
IGNORE_PREFIX          =

#---------------------------------------------------------------------------
# Configuration options related to the HTML output
#---------------------------------------------------------------------------
GENERATE_HTML          = $([ "$OUTPUT_FORMAT" = "html" ] && echo "YES" || echo "NO")
HTML_OUTPUT            = html
HTML_FILE_EXTENSION    = .html
HTML_HEADER            =
HTML_FOOTER            =
HTML_STYLESHEET        =
HTML_EXTRA_STYLESHEET  =
HTML_EXTRA_FILES       =
HTML_COLORSTYLE_HUE    = 220
HTML_COLORSTYLE_SAT    = 100
HTML_COLORSTYLE_GAMMA  = 80
HTML_TIMESTAMP         = YES
HTML_DYNAMIC_SECTIONS  = NO
HTML_INDEX_NUM_ENTRIES =
GENERATE_DOCSET        = NO
DOCSET_FEEDNAME        = "Doxygen generated docs"
DOCSET_BUNDLE_ID       = org.doxygen.Project
DOCSET_PUBLISHER_ID    = org.doxygen.Publisher
DOCSET_PUBLISHER_NAME  = Publisher
GENERATE_HTMLHELP      = NO
CHM_FILE               =
HHC_LOCATION           =
GENERATE_CHI           = NO
CHM_INDEX_ENCODING     =
BINARY_TOC             = NO
TOC_EXPAND             = NO
GENERATE_QHP           = NO
QCH_FILE               =
QHP_NAMESPACE          = org.doxygen.Project
QHP_VIRTUAL_FOLDER     = doc
QHP_CUST_FILTER_NAME   =
QHP_CUST_FILTER_ATTRS  =
QHP_SECT_FILTER_ATTRS  =
QHG_LOCATION           =
GENERATE_ECLIPSEHELP   = NO
ECLIPSE_DOC_ID         = org.doxygen.Project
DISABLE_INDEX          = NO
GENERATE_TREEVIEW      = NO
ENUM_VALUES_PER_LINE   = 4
TREEVIEW_WIDTH         = 250
EXT_LINKS_IN_WINDOW    = NO
FORMULA_FONTSIZE       = 10
FORMULA_TRANSPARENT    = YES
USE_MATHJAX            = NO
MATHJAX_FORMAT         = HTML-CSS
MATHJAX_RELPATH        = http://cdn.mathjax.org/mathjax/latest
MATHJAX_EXTENSIONS     =
MATHJAX_CODEFILE       =
SEARCHENGINE           = YES
SERVER_BASED_SEARCH    = NO
EXTERNAL_SEARCH        = NO
SEARCHENGINE_URL       =
SEARCHDATA_FILE        = searchdata.xml
EXTERNAL_SEARCH_ID     =
EXTRA_SEARCH_MAPPINGS  =

#---------------------------------------------------------------------------
# Configuration options related to the LaTeX output
#---------------------------------------------------------------------------
GENERATE_LATEX         = $([ "$OUTPUT_FORMAT" = "latex" ] && echo "YES" || echo "NO")
LATEX_OUTPUT           = latex
LATEX_CMD_NAME         = latex
MAKEINDEX_CMD_NAME     = makeindex
COMPACT_LATEX          = NO
PAPER_TYPE             = a4
EXTRA_PACKAGES         =
LATEX_HEADER           =
LATEX_FOOTER           =
LATEX_EXTRA_STYLESHEET =
LATEX_EXTRA_FILES      =
PDF_HYPERLINKS         = YES
USE_PDFLATEX           = YES
LATEX_BATCHMODE        = NO
LATEX_HIDE_INDICES     = NO
LATEX_SOURCE_CODE      = NO
LATEX_BIB_STYLE        = plain

#---------------------------------------------------------------------------
# Configuration options related to the man page output
#---------------------------------------------------------------------------
GENERATE_MAN           = $([ "$OUTPUT_FORMAT" = "man" ] && echo "YES" || echo "NO")
MAN_OUTPUT             = man
MAN_EXTENSION          = .3
MAN_SUBDIR             =
MAN_LINKS              = NO

#---------------------------------------------------------------------------
# Configuration options related to the XML output
#---------------------------------------------------------------------------
GENERATE_XML           = $([ "$OUTPUT_FORMAT" = "xml" ] && echo "YES" || echo "NO")
XML_OUTPUT             = xml
XML_PROGRAMLISTING     = YES

#---------------------------------------------------------------------------
# Configuration options related to the DOCBOOK output
#---------------------------------------------------------------------------
GENERATE_DOCBOOK       = NO
DOCBOOK_OUTPUT         = docbook
DOCBOOK_PROGRAMLISTING = NO

#---------------------------------------------------------------------------
# Configuration options for the AutoGen Definitions output
#---------------------------------------------------------------------------
GENERATE_AUTOGEN_DEF   = NO

#---------------------------------------------------------------------------
# Configuration options related to the Perl module output
#---------------------------------------------------------------------------
GENERATE_PERLMOD       = NO
PERLMOD_LATEX          = NO
PERLMOD_PRETTY         = YES
PERLMOD_MAKEVAR_PREFIX =

#---------------------------------------------------------------------------
# Configuration options related to the preprocessor
#---------------------------------------------------------------------------
ENABLE_PREPROCESSING   = YES
MACRO_EXPANSION        = YES
EXPAND_ONLY_PREDEF     = NO
SEARCH_INCLUDES        = YES
INCLUDE_PATH           = src/lib/inc
INCLUDE_FILE_PATTERNS  =
PREDEFINED             = DP_API= __cplusplus
EXPAND_AS_DEFINED      =
SKIP_FUNCTION_MACROS   = YES

#---------------------------------------------------------------------------
# Configuration options related to external references
#---------------------------------------------------------------------------
TAGFILES               =
GENERATE_TAGFILE       =
ALLEXTERNALS           = NO
EXTERNAL_GROUPS        = YES
EXTERNAL_PAGES         = YES
PERL_PATH              = /usr/bin/perl

#---------------------------------------------------------------------------
# Configuration options related to the dot tool
#---------------------------------------------------------------------------
CLASS_DIAGRAMS         = YES
MSCGEN_PATH            =
DIA_PATH               =
HIDE_UNDOC_RELATIONS   = YES
HAVE_DOT               = $(command -v dot >/dev/null 2>&1 && echo "YES" || echo "NO")
DOT_NUM_THREADS        = 0
DOT_FONTNAME           = Helvetica
DOT_FONTSIZE           = 10
DOT_FONTPATH           =
CLASS_GRAPH            = YES
COLLABORATION_GRAPH    = YES
GROUP_GRAPHS           = YES
UML_LOOK               = NO
UML_LIMIT_NUM_FIELDS   = 10
TEMPLATE_RELATIONS     = NO
INCLUDE_GRAPH          = YES
INCLUDED_BY_GRAPH      = YES
CALL_GRAPH             = YES
CALLER_GRAPH           = YES
GRAPHICAL_HIERARCHY    = YES
DIRECTORY_GRAPH        = YES
DOT_IMAGE_FORMAT       = png
INTERACTIVE_SVG        = NO
DOT_PATH               =
DOTFILE_DIRS           =
MSCFILE_DIRS           =
DIAFILE_DIRS           =
PLANTUML_JAR_PATH      =
PLANTUML_CFG_FILE      =
PLANTUML_INCLUDE_PATH  =
DOT_GRAPH_MAX_NODES    = 50
MAX_DOT_GRAPH_DEPTH    = 0
DOT_TRANSPARENT        = NO
DOT_MULTI_TARGETS      = YES
GENERATE_LEGEND        = YES
DOT_CLEANUP            = YES
EOF

    verbose "Doxygen configuration generated with $(wc -l < "$doxyfile") lines"
}

run_doxygen() {
    local doxyfile="$1"

    log "Generating documentation using Doxygen..."
    verbose "Output directory: $OUTPUT_DIR"
    verbose "Output format: $OUTPUT_FORMAT"

    if [[ $VERBOSE -eq 1 ]]; then
        doxygen "$doxyfile"
    else
        doxygen "$doxyfile" 2>/dev/null
    fi

    if [[ $? -eq 0 ]]; then
        log "Documentation generated successfully in $OUTPUT_DIR/$OUTPUT_FORMAT/"

        if [[ "$OUTPUT_FORMAT" = "html" ]]; then
            log "Open $OUTPUT_DIR/html/index.html in your browser to view the documentation"
        fi
    else
        error "Documentation generation failed"
    fi
}

cleanup() {
    if [[ -f "$DOXYFILE" ]]; then
        rm -f "$DOXYFILE"
        verbose "Cleaned up temporary Doxyfile: $DOXYFILE"
    fi
}

# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
# Main
# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;
        -c|--clean)
            CLEAN_FIRST=1
            shift
            ;;
        -p|--private)
            INCLUDE_PRIVATE=1
            shift
            ;;
        -v|--verbose)
            VERBOSE=1
            shift
            ;;
        -x|--extra)
            API_ONLY=0
            shift
            ;;
        -f|--format)
            if [[ -z "${2:-}" ]]; then
                error "Option $1 requires an argument"
            fi
            case "$2" in
                html|latex|man|xml)
                    OUTPUT_FORMAT="$2"
                    ;;
                *)
                    error "Invalid format: $2. Supported formats: html, latex, man, xml"
                    ;;
            esac
            shift 2
            ;;
        -o|--output)
            if [[ -z "${2:-}" ]]; then
                error "Option $1 requires an argument"
            fi
            OUTPUT_DIR="$2"
            shift 2
            ;;
        *)
            error "Unknown option: $1. Use -h for help."
            ;;
    esac
done

# Set trap for cleanup
trap cleanup EXIT

# Check prerequisites
check_doxygen

# Clean if requested
if [[ $CLEAN_FIRST -eq 1 ]]; then
    clean_docs
fi

# Generate documentation
generate_doxyfile "$DOXYFILE" "$INCLUDE_PRIVATE"
run_doxygen "$DOXYFILE"

log "Documentation generation completed successfully!"
